const App=(()=>{function modal(html){document.getElementById('modalBody').innerHTML=html;document.getElementById('modal').classList.remove('hidden');document.getElementById('modal').setAttribute('aria-hidden','false')}function closeModal(){document.getElementById('modal').classList.add('hidden');document.getElementById('modalBody').replaceChildren()}function applyTheme(){const s=StorageService.settings();document.body.classList.toggle('light',s.theme==='light');document.documentElement.style.setProperty('--user-accent',s.accent==='magenta'?'#ff4fd8':s.accent==='green'?'#62ff9a':'#35d9ff');document.documentElement.style.setProperty('--user-font-scale',String(s.fontScale||1));document.body.classList.toggle('reduced-custom-motion',s.animations===false);document.body.classList.toggle('compact-custom',s.quickCompact===true);document.getElementById('themeBtn').textContent=s.theme==='dark'?'☀️':'🌙'}function counters(){const d=StorageService.data();document.getElementById('memberCount').textContent=d.members.length;
    document.getElementById('activityCount').textContent=d.activities.length;
    document.getElementById('badgeCount').textContent=d.badges.length;
    document.getElementById('taskCount').textContent=d.tasks.length}function refresh(){applyTheme();I18n.apply();Members.render();Activities.render();Games.init();Chat.renderConversations();counters();updateStatus()}async function updateStatus(){try{await StorageService.flush()}catch{}
  let online=false;
  if(window.SupabaseService?.configured()){try{await SupabaseService.health();online=true}catch{}}
  document.getElementById('connectionStatus').textContent=online?'Online':I18n.t('offline');
  document.getElementById('modeBadge').textContent=online?`🟢 ${I18n.t('online')}`:`🟠 ${I18n.t('offline').toUpperCase()}`;
}
function firstLogin(user){
  if(!user?.id)return; const key=`scoutHub.firstLogin.${user.id}`; if(localStorage.getItem(key)==='1')return; localStorage.setItem(key,'1');
  const box=document.createElement('div'); box.className='welcome-overlay'; box.innerHTML=`<div class="welcome-card"><div class="welcome-fleur">⚜️</div><div class="welcome-orbit">🧭</div><h1>Byenveni nan SCOUT HUB</h1><p>Kont ou konekte avèk siksè.</p><div class="welcome-sparkles">✦ ⚜ ✦ ⚜ ✦</div><button class="primary-btn">Kòmanse</button></div>`; document.body.appendChild(box); requestAnimationFrame(()=>box.classList.add('show')); box.querySelector('button').onclick=()=>{box.classList.remove('show');setTimeout(()=>box.remove(),450)}; setTimeout(()=>box.querySelector('button')?.click(),6500);
}
function badgeCelebration(b){const box=document.createElement('div');box.className='badge-celebration';box.innerHTML=`<div class="badge-burst">⚜️ ✦ ⚜️</div><div class="badge-card"><div class="badge-icon-big">${Utils.esc(b?.icon||'🏅')}</div><h2>Nouvo badge!</h2><strong>${Utils.esc(b?.title||b?.name||'Felisitasyon!')}</strong><p>Ou fè yon bèl pwogrè nan SCOUT HUB. 🥰</p><button class="primary-btn">Kontinye</button></div>`;document.body.appendChild(box);requestAnimationFrame(()=>box.classList.add('show'));box.querySelector('button').onclick=()=>{box.classList.remove('show');setTimeout(()=>box.remove(),420)};setTimeout(()=>box.querySelector('button')?.click(),7000);}
async function init(){
Sound?.init?.(); NotificationCenter?.init?.(); ScoutMusic?.init?.(); SessionManager?.init?.().then(()=>Realtime?.start?.()).catch(e=>console.warn('[SESSION]',e.message)); document.getElementById('notifyBtn')?.addEventListener('click',()=>NotificationCenter.inbox());document.getElementById('modalClose').onclick=closeModal;document.getElementById('modal').addEventListener('click',e=>{if(e.target.id==='modal')closeModal()});
    try{await Auth.restore(); if(window.SupabaseService?.configured()) await StorageService.hydrate();}catch(e){console.warn('[SCOUT HUB] startup sync:',e.message)}
    window.addEventListener('scout:session',e=>{updateStatus();firstLogin(e.detail?.user||Auth.get());if(e.detail?.user)Realtime?.start?.();});
    window.addEventListener('scout:badge-earned',e=>badgeCelebration(e.detail||{}));
    window.addEventListener('scout:announcement',e=>{if(document.visibilityState==='visible')NotificationCenter.banner(`📢 ${e.detail?.title||'Nouvel anons'}`,e.detail?.content||e.detail?.body||'Nouvo anons pou tout gwoup la.','📢','announcement');}); Navigation.init();Members.init();Activities.init();Games.init();Chat.init();Media.init();Voice.init();Features.init();Settings.init();applyTheme();I18n.apply();counters();updateStatus();firstLogin(Auth.get()); window.addEventListener('scout:realtime',()=>{try{counters();}catch{}}); window.addEventListener('online',async()=>{await StorageService.flush();await StorageService.hydrate();refresh();updateStatus();});window.addEventListener('offline',updateStatus)}return{init,modal,closeModal,applyTheme,counters,refresh}})();document.addEventListener('DOMContentLoaded',App.init);
