const ScoutMusic=(()=>{
  let audio=null,tracks=[],current=-1,siteTracks=[],isLeader=false,loopEnabled=false;
  const STORE='scoutHub.music.v2';
  function load(){try{tracks=JSON.parse(localStorage.getItem(STORE)||'[]')}catch{tracks=[]}}
  async function loadSite(){siteTracks=[];try{const c=SupabaseService?.getClient?.();if(c&&Auth.get()){const {data}=await c.from('music_tracks').select('*').eq('active',true).order('sort_order',{ascending:true}).order('created_at',{ascending:true});if(Array.isArray(data))siteTracks=data.map(t=>({name:t.title,artist:t.artist,src:t.audio_url,icon:t.icon||'🎵',site:true,id:t.id}));}}catch{} if(!siteTracks.length){try{const r=await fetch('./music/library.json',{cache:'no-store'});if(r.ok)siteTracks=await r.json();}catch{siteTracks=[]}}}
  function all(){return [...siteTracks.map((t,i)=>({...t,site:true,index:i})),...tracks.map((t,i)=>({...t,site:false,index:i}))]}
  function row(t,i){return `<div class="music-track ${current===i?'playing':''}"><span class="music-cover">${Utils.esc(t.icon||'🎵')}</span><div><strong>${Utils.esc(t.name||'Track')}</strong><small>${Utils.esc(t.artist||'Scout Music')}${t.site?' • Sit':' • Lokal'}${t.durationLabel?` • ${Utils.esc(t.durationLabel)}`:''}</small></div><button data-play-track="${i}" class="secondary-btn">▶️</button>${t.site&&t.id&&isLeader?`<button data-delete-site-track="${Utils.esc(t.id)}" class="icon-btn" title="Retire">×</button>`:(!t.site?`<button data-remove-track="${i}" class="icon-btn">×</button>`:'')}</div>`}
  function renderInto(list){if(!list)return;const a=all();list.innerHTML=a.length?a.map(row).join(''):'<p class="muted">Pa gen mizik ankò. Ajoute mizik ou oswa mete track sit yo nan music/library.json.</p>';list.onclick=async e=>{const p=e.target.closest('[data-play-track]'),r=e.target.closest('[data-remove-track]'),d=e.target.closest('[data-delete-site-track]');if(p)play(+p.dataset.playTrack);if(r){const idx=+r.dataset.removeTrack;tracks.splice(idx-siteTracks.length,1);save();render();}if(d&&isLeader){try{await SupabaseService.getClient().from('music_tracks').delete().eq('id',d.dataset.deleteSiteTrack);await loadSite();render();}catch{}}}}
  function save(){try{localStorage.setItem(STORE,JSON.stringify(tracks.map(({name,artist,src})=>({name,artist,src}))))}catch{}}
  function render(){renderInto(document.getElementById('musicListPage'));renderInto(document.getElementById('musicList'))}
  function addFiles(files){for(const f of [...files].filter(f=>f.type.startsWith('audio/'))){tracks.push({name:f.name,artist:'Fichye lokal',src:URL.createObjectURL(f)})}save();render()}
  function play(i){const t=all()[i];if(!t)return;const a=document.getElementById('scoutAudioPage')||document.getElementById('scoutAudio');if(!a)return;a.src=t.src;a.loop=loopEnabled;a.play().catch(()=>{});audio=a;current=i;render();a.onended=()=>{if(loopEnabled)return;const next=(i+1)%all().length;if(all().length>1)play(next)}}
  async function open(){await loadSite();isLeader=!!StorageService.collection('members').find(m=>m.user_id===Auth.get()?.id&&['admin','leader'].includes(m.role));App.modal(`<div class="music-player"><div class="music-hero"><div>🎶</div><div><h2>Scout Music</h2><p>Bibliyotèk mizik sit la + mizik ou chwazi sou telefòn ou.</p></div></div><label class="music-import primary-btn">➕ Ajoute mizik<input id="musicFiles" type="file" accept="audio/*" multiple hidden></label><div id="musicList" class="music-list"></div><div class="music-controls"><button id="musicLoop" class="secondary-btn" type="button">🔁 Loop: <span>${loopEnabled?'ON':'OFF'}</span></button><button id="musicNext" class="secondary-btn" type="button">⏭️ Suivant</button></div><audio id="scoutAudio" controls preload="metadata"></audio></div>`);document.getElementById('musicFiles').onchange=e=>addFiles(e.target.files);document.getElementById('musicLoop').onclick=()=>{loopEnabled=!loopEnabled;const a=document.getElementById('scoutAudio');if(a)a.loop=loopEnabled;const b=document.querySelector('#musicLoop span');if(b)b.textContent=loopEnabled?'ON':'OFF';};document.getElementById('musicNext').onclick=()=>{const n=all().length?(current+1+all().length)%all().length:-1;if(n>=0)play(n)}; if(isLeader){const form=document.createElement('div');form.className='site-music-admin';form.innerHTML='<hr><strong>⚙️ Gérer la musique du site</strong><div class="music-admin-grid"><input id="siteMusicTitle" placeholder="Titre"><input id="siteMusicArtist" placeholder="Artiste"><input id="siteMusicUrl" placeholder="URL audio HTTPS"><button id="siteMusicAdd" class="secondary-btn">➕ Ajouter au site</button></div>';document.querySelector('.music-player')?.appendChild(form);document.getElementById('siteMusicAdd').onclick=async()=>{const title=document.getElementById('siteMusicTitle').value.trim(),artist=document.getElementById('siteMusicArtist').value.trim()||'Scout Music',url=document.getElementById('siteMusicUrl').value.trim();if(!title||!/^https:\/\//i.test(url))return NotificationCenter.banner('Musique','Mete yon URL audio HTTPS valid.','⚠️','warning');try{const c=SupabaseService.getClient();const {error}=await c.from('music_tracks').insert({title,artist,audio_url:url,created_by:Auth.get()?.id||null});if(error)throw error;await loadSite();render();NotificationCenter.inApp('🎵 Mizik ajoute',title,'🎵','music')}catch(err){NotificationCenter.banner('Mizik',err.message||'Pa kapab ajoute mizik la.','⚠️','warning')}};}render()}
  function stop(){if(audio){audio.pause();audio.currentTime=0}}
  async function init(){load();await loadSite();const input=document.getElementById('musicFilesPage');if(input)input.onchange=e=>addFiles(e.target.files);const lp=document.getElementById('musicLoopPage');if(lp)lp.onclick=()=>{loopEnabled=!loopEnabled;const a=document.getElementById('scoutAudioPage');if(a)a.loop=loopEnabled;const b=lp.querySelector('span');if(b)b.textContent=loopEnabled?'ON':'OFF';};const np=document.getElementById('musicNextPage');if(np)np.onclick=()=>{const n=all().length?(current+1+all().length)%all().length:-1;if(n>=0)play(n)};render();window.addEventListener('scout:pagechange',e=>{if(e.detail?.page==='lessonsPage')stop()})}
  return {init,open,stop};
})();if (typeof window !== 'undefined') window.ScoutMusic = ScoutMusic;
