const StorageService=(()=>{
  const K='scoutHub.v2';
  const defaults={members:[],activities:[],tasks:[],badges:[],skills:[],announcements:[],messages:[],attendance:[],notes:[],patrols:[],settings:{theme:'dark',language:'ht',activeMemberId:null,sound:true,vibration:false,notifications:false,accent:'cyan',fontScale:1,animations:true,quickCompact:false},outbox:[]};
  const tables=['members','activities','tasks','badges','skills','announcements','messages','attendance','notes','patrols'];
  const pendingSync=new Set();
  const clone=()=>JSON.parse(JSON.stringify(defaults));
  function read(){try{return JSON.parse(localStorage.getItem(K))||clone()}catch{return clone()}}
  function normalize(d){for(const k of tables)if(!Array.isArray(d[k]))d[k]=[];d.settings={...defaults.settings,...(d.settings||{})};if(!Array.isArray(d.outbox))d.outbox=[];return d}
  const data=()=>normalize(read());
  const write=d=>{localStorage.setItem(K,JSON.stringify(normalize(d)));return d};
  const collection=name=>data()[name]||[];
  const uid=()=>crypto?.randomUUID?.()||('local-'+Date.now()+'-'+Math.random().toString(16).slice(2));
  const remote=()=>window.SupabaseService?.configured()?SupabaseService.getClient():null;
  function toRemote(name,row){const r={...row};delete r._localOnly;delete r.peer_local_id;delete r.sender;delete r.type;delete r.date;delete r.time;delete r.assigned_member_id;delete r.name;delete r.content_local;if(name!=='badges')delete r.member_id;if(name==='members'){r.member_code=row.member_id||row.member_code;r.created_by=r.created_by||row.user_id||null}if(name==='activities'){r.activity_date=row.date||row.activity_date;r.activity_time=row.time||row.activity_time||null}if(name==='tasks'){r.assigned_member_id=row.assigned_member_id||row.assigned_to||null;r.status=row.completed?'done':(row.status||'todo');delete r.assigned_to}if(name==='badges'){r.member_id=row.member_id||null;r.source_task_id=row.source_task_id||null;r.auto_awarded=!!row.auto_awarded}if(name==='skills'){r.skill_name=row.name||row.skill_name;r.progress=Number(row.progress||0);delete r.last_task_id;delete r.source_task_id}if(name==='announcements'){r.body=row.content||row.body;r.created_by=r.created_by||Auth?.get?.()?.id||null;delete r.date}if(name==='messages'){r.sender_id=row.sender_member_id||row.sender_id;r.sender_member_id=row.sender_member_id;r.receiver_member_id=row.receiver_member_id;r.sender_user_id=row.sender_user_id;r.content=row.file_path?null:row.content;r.file_path=row.file_path||null;delete r.sync_status}
    if(name==='notes'){r.created_by=r.created_by||Auth?.get?.()?.id||null}
    if(name==='attendance'){r.date=row.date}
    if(name==='patrols'){r.name=row.name;r.leader=row.leader||''}return r}
  function fromRemote(name,row){const r={...row};if(name==='members'){r.member_id=r.member_id||r.member_code;r.user_id=r.user_id||r.created_by||null}if(name==='activities'){r.date=r.activity_date;r.time=r.time||(r.activity_time?String(r.activity_time).slice(0,5):'')}if(name==='tasks'){r.assigned_member_id=r.assigned_member_id||r.assigned_to||null;r.completed=!!r.completed||r.status==='done'}if(name==='skills'){r.name=r.name||r.skill_name;r.progress=Number(r.progress??(r.level==='avancé'?100:r.level==='intermédiaire'?60:25))}if(name==='badges'){r.name=r.name||r.title;r.title=r.title||r.name}if(name==='announcements'){r.content=r.content??r.body;r.date=r.date||r.created_at}if(name==='messages'){r.message_type=r.message_type==='audio'?'voice':r.message_type;r.content=r.content||'';r.peer_local_id=r.peer_local_id}return r}
  function queue(op){const d=data();d.outbox.push(op);write(d)}
  async function remoteUpsert(name,row){const c=remote();if(!c)return false;const {data:r,error}=await c.from(name).upsert(toRemote(name,row),{onConflict:'id'}).select().single();if(error)throw error;return fromRemote(name,r)}
  async function flush(){const c=remote();if(!c||!Auth?.get?.())return false;
    if(pendingSync.size) await Promise.allSettled([...pendingSync]);
    const d=data();const pending=[...d.outbox];if(!pending.length)return true;const remain=[];for(const op of pending){try{if(op.kind==='delete'){const {error}=await c.from(op.name).delete().eq('id',op.id);if(error)throw error}else{await remoteUpsert(op.name,op.row)}}catch(e){remain.push(op);console.warn('[SCOUT HUB] queued sync:',op.name,e.message)}}d.outbox=remain;write(d);return remain.length===0}
  async function pull(name){const c=remote();if(!c)return null;try{const {data:rows,error}=await c.from(name).select('*').order('created_at',{ascending:true});if(error)throw error;return(rows||[]).map(x=>fromRemote(name,x))}catch(e){console.warn('[SCOUT HUB] sync read:',name,e.message);return null}}
  async function hydrate(){if(!remote()||!Auth.get())return false;await flush();const before=data();const dirty=new Map();for(const op of before.outbox)if(op.kind!=='delete')dirty.set(`${op.name}:${op.row.id}`,op.row);for(const row of before.messages||[])if(row.sync_status==='pending')dirty.set(`messages:${row.id}`,row);const removed=new Set(before.outbox.filter(x=>x.kind==='delete').map(x=>`${x.name}:${x.id}`));let changed=false;for(const name of tables){const rows=await pull(name);if(rows!==null){const merged=rows.filter(r=>!removed.has(`${name}:${r.id}`));for(const [key,row] of dirty)if(key.startsWith(name+':')){const i=merged.findIndex(r=>String(r.id)===String(row.id));if(i>=0)merged[i]=row;else merged.push(row)}const d=data();d[name]=merged;write(d);changed=true}}return changed}
  function add(name,x){const d=data(),u=Auth?.get?.();const base={id:uid(),created_at:new Date().toISOString(),...x};if(u?.id&&name==='notes')base.created_by=u.id;if(u?.id&&(name==='members'||name==='activities'||name==='announcements')){base.created_by=base.created_by||u.id;if(name==='members')base.user_id=base.user_id||u.id}const r=base;d[name].push(r);write(d);
    // Auto task badges are created by the Supabase task trigger. Keep the optimistic local badge, but do not send a second client insert.
    if(!((name==='badges'||name==='skills')&&r.auto_awarded)){const p=remoteUpsert(name,r).catch(()=>queue({kind:'upsert',name,row:r}));pendingSync.add(p);p.finally(()=>pendingSync.delete(p));}
    return r}
  function update(name,id,x){const d=data(),i=d[name].findIndex(v=>String(v.id)===String(id));if(i<0)return null;d[name][i]={...d[name][i],...x};const r=d[name][i];write(d);if(!((name==='badges'||name==='skills')&&r.auto_awarded)){const p=remoteUpsert(name,r).catch(()=>queue({kind:'upsert',name,row:r}));pendingSync.add(p);p.finally(()=>pendingSync.delete(p));}return r}
  function remove(name,id){const d=data();d[name]=d[name].filter(v=>String(v.id)!==String(id));write(d);void (async()=>{try{const c=remote();if(!c||!Auth?.get?.())throw new Error('offline');const {error}=await c.from(name).delete().eq('id',id);if(error)throw error}catch{queue({kind:'delete',name,id})}})()}
  const settings=()=>data().settings;function setSettings(s){const d=data();d.settings={...d.settings,...s};write(d)}function clear(){localStorage.removeItem(K)}function exportData(){return JSON.stringify({app:'SCOUT HUB ONLINE',schema:5,exported_at:new Date().toISOString(),data:data()},null,2)}function importData(raw){const p=JSON.parse(raw);if(!p?.data||!Array.isArray(p.data.members)||!Array.isArray(p.data.activities))throw new Error('INVALID_BACKUP');const d=data();for(const k of tables)if(Array.isArray(p.data[k]))d[k]=p.data[k];if(p.data.settings)d.settings={...d.settings,...p.data.settings};write(d)}
  return{data,collection,add,update,remove,settings,setSettings,clear,exportData,importData,hydrate,flush,queue};
})();
